import { Toilet, Comment, User } from './types';

// Mock data for development purposes
export const mockToilets: Toilet[] = [
  {
    id: '1',
    name: 'Central Park Restroom',
    address: '5 Avenue & 59th Street',
    latitude: 40.7649,
    longitude: -73.9759,
    status: 'available',
    features: ['wheelchair_accessible', 'baby_changing', 'free'],
    rating: 4.2,
    addedBy: 'user1',
    addedAt: '2023-01-15T12:00:00Z',
    updatedAt: '2023-06-10T14:30:00Z',
  },
  {
    id: '2',
    name: 'Municipal Building Facilities',
    address: '1 Centre Street',
    latitude: 40.7127,
    longitude: -74.0059,
    status: 'occupied',
    features: ['wheelchair_accessible', 'gender_neutral'],
    rating: 3.8,
    addedBy: 'user2',
    addedAt: '2023-02-05T10:15:00Z',
    updatedAt: '2023-06-12T09:45:00Z',
  },
  {
    id: '3',
    name: 'Union Square Public Restroom',
    address: 'Union Square West',
    latitude: 40.7359,
    longitude: -73.9911,
    status: 'closed',
    features: ['wheelchair_accessible', 'free', '24h'],
    rating: 4.0,
    addedBy: 'user1',
    addedAt: '2023-01-20T15:30:00Z',
    updatedAt: '2023-06-11T11:20:00Z',
  },
  {
    id: '4',
    name: 'Bryant Park Restroom',
    address: '42 W 42nd St',
    latitude: 40.7536,
    longitude: -73.9832,
    status: 'available',
    features: ['wheelchair_accessible', 'baby_changing', 'free', 'gender_neutral'],
    rating: 4.7,
    addedBy: 'user3',
    addedAt: '2023-03-10T09:00:00Z',
    updatedAt: '2023-06-13T16:45:00Z',
  },
  {
    id: '5',
    name: 'Times Square Visitor Center',
    address: '1560 Broadway',
    latitude: 40.7589,
    longitude: -73.9851,
    status: 'available',
    features: ['wheelchair_accessible', 'requires_key'],
    rating: 3.5,
    addedBy: 'user2',
    addedAt: '2023-02-25T14:20:00Z',
    updatedAt: '2023-06-12T13:10:00Z',
  },
];

export const mockComments: Comment[] = [
  {
    id: '1',
    toiletId: '1',
    userId: 'user2',
    userName: 'Jane Smith',
    userImage: 'https://randomuser.me/api/portraits/women/65.jpg',
    text: 'Very clean facilities. Highly recommended!',
    rating: 5,
    createdAt: '2023-05-15T10:30:00Z',
  },
  {
    id: '2',
    toiletId: '1',
    userId: 'user3',
    userName: 'Mike Johnson',
    userImage: 'https://randomuser.me/api/portraits/men/32.jpg',
    text: 'Good location but could be cleaner.',
    rating: 3,
    createdAt: '2023-05-20T14:45:00Z',
  },
  {
    id: '3',
    toiletId: '2',
    userId: 'user1',
    userName: 'John Doe',
    userImage: 'https://randomuser.me/api/portraits/men/22.jpg',
    text: 'Hard to find but decent once you get there.',
    rating: 4,
    createdAt: '2023-05-18T09:15:00Z',
  },
  {
    id: '4',
    toiletId: '4',
    userId: 'user3',
    userName: 'Mike Johnson',
    userImage: 'https://randomuser.me/api/portraits/men/32.jpg',
    text: 'Exceptionally clean and well-maintained!',
    rating: 5,
    createdAt: '2023-05-22T16:20:00Z',
  },
];

export const mockUsers: User[] = [
  {
    id: 'user1',
    name: 'John Doe',
    email: 'john@example.com',
    role: 'admin',
    image: 'https://randomuser.me/api/portraits/men/22.jpg',
  },
  {
    id: 'user2',
    name: 'Jane Smith',
    email: 'jane@example.com',
    role: 'citizen',
    image: 'https://randomuser.me/api/portraits/women/65.jpg',
  },
  {
    id: 'user3',
    name: 'Mike Johnson',
    email: 'mike@example.com',
    role: 'citizen',
    image: 'https://randomuser.me/api/portraits/men/32.jpg',
  },
];